export interface Product {
    id: number
    name: string
    description: string
    price: number
    quantity: number
    createdAt: Date
    updatedAt: Date
}

// For creating a new product (ID and timestamps are generated by the server)
export type CreateProductDto = Omit<Product, 'id' | 'createdAt' | 'updateAt'>

// For updating a product (all fields are optional, and ID is in the URL)
export type UpdateProductDto = Partial<CreateProductDto> 

